variable "pm_api_url" {}
variable "token_id" {}
variable "token_secret" {}
variable "ssh_key1" {}
variable "ssh_key2" {}
variable "img_type" {}
variable "cores" {}
variable "memory" {}
variable "ip" {}
variable "gw" {}
variable "count_vm" {}
variable "proxmox_host" {}
